In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv(r"C:\Users\ASUS\Downloads\archive (7)\Heart Attack.csv")

In [3]:
data.head()

age  gender  impluse  pressurehight  pressurelow  glucose    kcm  troponin  \
0   64       1       66            160           83    160.0   1.80     0.012   
1   21       1       94             98           46    296.0   6.75     1.060   
2   55       1       64            160           77    270.0   1.99     0.003   
3   64       1       70            120           55    270.0  13.87     0.122   
4   55       1       64            112           65    300.0   1.08     0.003   

      class  
0  negative  
1  positive  
2  negative  
3  positive  
4  negative

In [4]:
data.tail()

age  gender  impluse  pressurehight  pressurelow  glucose    kcm  \
1314   44       1       94            122           67    204.0   1.63   
1315   66       1       84            125           55    149.0   1.33   
1316   45       1       85            168          104     96.0   1.24   
1317   54       1       58            117           68    443.0   5.80   
1318   51       1       94            157           79    134.0  50.89   

      troponin     class  
1314     0.006  negative  
1315     0.172  positive  
1316     4.250  positive  
1317     0.359  positive  
1318     1.770  positive

In [5]:
data.sample(15)

age  gender  impluse  pressurehight  pressurelow  glucose      kcm  \
535    55       0       67            155           89     97.0   22.910   
89     61       1       60            202           88    111.0    0.633   
5      58       0       61            112           58     87.0    1.830   
781    78       0       89            214           88    434.0    7.260   
909    85       0       72            117           49    272.0   81.650   
974    46       0       80            129           89     99.0    2.380   
403    78       1       68            176          106    122.0    0.755   
510    52       1       77            122           58    122.0   51.900   
337    48       0       74            118           78    141.0   18.960   
28     47       0       66            134           57    279.0  300.000   
513    42       1       94             98           46    123.0    1.300   
1111   56       0       71            119           76    321.0   43.510   
773    70       1       89            100           50    314.0    0.880   
877    60       1       94            122           67    115.0    2.100   
149    69       1       82             86           70     87.0    4.370   

      troponin     class  
535      0.119  positive  
89       6.050  positive  
5        0.004  negative  
781      0.009  positive  
909      0.015  positive  
974      0.710  positive  
403      0.492  positive  
510      0.017  positive  
337      0.007  positive  
28       0.007  positive  
513      0.006  negative  
1111     0.003  positive  
773      0.406  positive  
877      2.200  positive  
149      0.017  positive

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   age            1319 non-null   int64  
 1   gender         1319 non-null   int64  
 2   impluse        1319 non-null   int64  
 3   pressurehight  1319 non-null   int64  
 4   pressurelow    1319 non-null   int64  
 5   glucose        1319 non-null   float64
 6   kcm            1319 non-null   float64
 7   troponin       1319 non-null   float64
 8   class          1319 non-null   object 
dtypes: float64(3), int64(5), object(1)
memory usage: 92.9+ KB


In [7]:
data.describe()

age       gender      impluse  pressurehight  pressurelow  \
count  1319.000000  1319.000000  1319.000000    1319.000000  1319.000000   
mean     56.191812     0.659591    78.336619     127.170584    72.269143   
std      13.647315     0.474027    51.630270      26.122720    14.033924   
min      14.000000     0.000000    20.000000      42.000000    38.000000   
25%      47.000000     0.000000    64.000000     110.000000    62.000000   
50%      58.000000     1.000000    74.000000     124.000000    72.000000   
75%      65.000000     1.000000    85.000000     143.000000    81.000000   
max     103.000000     1.000000  1111.000000     223.000000   154.000000   

           glucose          kcm     troponin  
count  1319.000000  1319.000000  1319.000000  
mean    146.634344    15.274306     0.360942  
std      74.923045    46.327083     1.154568  
min      35.000000     0.321000     0.001000  
25%      98.000000     1.655000     0.006000  
50%     116.000000     2.850000     0.014000  
75%     169.500000     5.805000     0.085500  
max     541.000000   300.000000    10.300000

In [8]:
data.shape

(1319, 9)

In [9]:
data.size

11871

In [10]:
data.isnull().sum()

age              0
gender           0
impluse          0
pressurehight    0
pressurelow      0
glucose          0
kcm              0
troponin         0
class            0
dtype: int64

In [11]:
data.age.value_counts()

age
60     106
70      73
50      68
63      64
65      62
      ... 
88       1
100      1
14       1
91       1
84       1
Name: count, Length: 75, dtype: int64

In [12]:
data['class'].value_counts()

class
positive    810
negative    509
Name: count, dtype: int64

In [13]:
negative = data[data['class'] == "negative"]
positive = data[data['class'] == "positive"]

In [14]:
negative.shape

(509, 9)

In [15]:
positive.shape

(810, 9)

In [16]:
positive_sample = positive.sample(n=509)
positive_sample.shape

(509, 9)

In [17]:
newdata = pd.concat([positive_sample , negative], axis=0)

In [18]:
newdata.sample(15)

age  gender  impluse  pressurehight  pressurelow  glucose     kcm  \
991    55       1       70            120           55    334.0    2.49   
989    55       1       94             98           46     87.0    1.93   
957    61       1       69            148           72     95.0    1.48   
638    48       0       69            103           68    115.0    8.34   
106    50       1       83            140           81    244.0    3.27   
875    47       1       79            156           82    206.0    6.13   
15     61       1       81            118           66    134.0    1.49   
920    28       1       68             91           61    239.0  208.60   
1154   71       0       60            124          100    200.0    1.18   
767    42       1       81            150           51    101.0    1.41   
180    60       1       60            120           60    126.0    1.30   
1195   39       1       59            164           75    177.0    3.29   
3      64       1       70            120           55    270.0   13.87   
458    55       1      112            100           72    132.0    2.57   
827    50       1       66            112           74    146.0   10.11   

      troponin     class  
991      0.008  negative  
989      0.010  negative  
957      0.003  negative  
638      0.003  positive  
106      2.230  positive  
875      0.004  negative  
15       0.017  positive  
920      0.003  positive  
1154     0.014  negative  
767      0.003  negative  
180      0.046  positive  
1195     0.003  negative  
3        0.122  positive  
458      1.630  positive  
827      1.400  positive

In [19]:
newdata['class'].value_counts()

class
positive    509
negative    509
Name: count, dtype: int64

In [20]:
newdata.shape

(1018, 9)

In [21]:
X=newdata.drop("class" , axis="columns")
X.head()

age  gender  impluse  pressurehight  pressurelow  glucose    kcm  \
245    59       1       60             86           50    104.0   2.35   
298    60       1       83            126           76    246.0   2.90   
740    60       0       72            138           86    124.0  15.88   
1156   64       0      117            112           74    146.0   2.88   
1024   65       1       36            106           58     88.0   1.25   

      troponin  
245      0.019  
298      0.019  
740      0.043  
1156     0.088  
1024     0.088

In [22]:
X.shape

(1018, 8)

In [23]:
Y=newdata['class'].values

In [24]:
Y

array(['positive', 'positive', 'positive', ..., 'negative', 'negative',
       'negative'], dtype=object)

In [25]:
Y.shape

(1018,)

In [26]:
print(Y)

['positive' 'positive' 'positive' ... 'negative' 'negative' 'negative']


In [27]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

In [28]:
Y

array([1, 1, 1, ..., 0, 0, 0])

In [29]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , Y , test_size= 0.2)

In [30]:
len(X_train)

814

In [31]:
len(X_test)

204

In [32]:
len(y_train)

814

In [33]:
len(y_test)

204

In [34]:
X_train.shape

(814, 8)

In [35]:
y_train.shape

(814,)

In [36]:
X_train.head()

age  gender  impluse  pressurehight  pressurelow  glucose   kcm  \
494    37       1       59            125           72    122.0  0.78   
76     47       0       64            101           68    147.0  7.65   
314    53       0       64            154           97     82.0  2.25   
140    45       0       79             87           47     82.0  2.38   
1168   33       0       74            119           78    102.0  2.57   

      troponin  
494      0.003  
76       0.006  
314      0.017  
140      0.003  
1168     0.003

In [37]:
y_train

array([0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,

In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [39]:
lrmodel = LogisticRegression()
lrmodel.fit(X_train , y_train)

C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [40]:
lrmodel.predict(X_test)

array([1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0])

In [41]:
from sklearn.metrics import accuracy_score
X_train_prediction = lrmodel.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction , y_train)

In [42]:
training_data_accuracy

0.7985257985257985

In [43]:
from sklearn.metrics import accuracy_score
X_test_prediction = lrmodel.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_prediction , y_test)

In [44]:
testing_data_accuracy

0.8235294117647058

In [45]:
dtmodel = DecisionTreeClassifier(random_state=42)
dtmodel.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [46]:
from sklearn.metrics import accuracy_score
X_train_prediction = dtmodel.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction , y_train)

In [47]:
training_data_accuracy

1.0

In [48]:
from sklearn.metrics import accuracy_score
X_test_prediction = dtmodel.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_prediction , y_test)

In [49]:
testing_data_accuracy

0.9852941176470589

In [50]:
'''
Age
gender(0 for Female, 1 for Male)
heart rate (impulse)
systolic BP (pressurehight)
diastolic BP (pressurelow)
blood sugar(glucose)
CK-MB (kcm)
Test-Troponin (troponin)
negative refers to the absence of a heart attack, while positive refers to the presence of a heart attack
'''

'\nAge\ngender(0 for Female, 1 for Male)\nheart rate (impulse)\nsystolic BP (pressurehight)\ndiastolic BP (pressurelow)\nblood sugar(glucose)\nCK-MB (kcm)\nTest-Troponin (troponin)\nnegative refers to the absence of a heart attack, while positive refers to the presence of a heart attack\n'

In [51]:
dtmodel.predict([[64,1,66,160,83,160.0,1.80,0.012]])

C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])

In [52]:
input_data = (64,1,66,160,83,160.0,1.80,0.012)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1 , -1)
prediction = dtmodel.predict(input_data_reshaped)
prediction = le.inverse_transform(prediction)
prediction

C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array(['negative'], dtype=object)

In [53]:
input_data = (64,1,66,160,83,160.0,1.80,0.012)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1 , -1)
prediction = dtmodel.predict(input_data_reshaped)
prediction = le.inverse_transform(prediction)
if prediction == "negative":
   print("The person does not have Heart attack problem.")
else:
   print("The person has Heart attack problem.")

The person does not have Heart attack problem.


C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [54]:
import pickle
with open("Heart_model_pickle" , "wb") as file:
     pickle.dump(dtmodel , file)

In [55]:
import numpy as np
import pickle
with open("Heart_model_pickle" , "rb") as file:
     dtmodel = pickle.load(file)

In [56]:
input_data = (64,1,66,160,83,160.0,1.80,0.012)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1 , -1)
prediction = dtmodel.predict(input_data_reshaped)
prediction = le.inverse_transform(prediction)
if prediction == "negative":
   print("The person does not have Heart attack problem.")
else:
   print("The person has Heart attack problem.")

The person does not have Heart attack problem.


C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [57]:
#age in years
age = int(input(""))
#gender(0 for Female, 1 for Male)
gender = int(input(""))
#impluse
impluse = int(input(""))
#pressurehight
pressurehight = int(input(""))
#pressurelow
pressurelow = int(input(""))
#glucose
glucose = float(input(""))
#kcm
kcm = float(input(""))
#troponin
troponin = float(input(""))

 64
 1
 66
 160
 83
 160.0
 1.80
 0.012


In [58]:
input_data = (age,gender,impluse,pressurehight,pressurelow,glucose,kcm,troponin)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1 , -1)
prediction = dtmodel.predict(input_data_reshaped)
prediction = le.inverse_transform(prediction)
if prediction == "negative":
   print("The person does not have Heart attack problem.")
else:
   print("The person has Heart attack problem.")

The person does not have Heart attack problem.


C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
